### ISSUE TITLE
CentOS 5.11 images are broken for some use cases

### ISSUE THREAD

**Issue by jkugler** [grtjn/centos-packer-templates#2]
If using rsync folders on Vagrant VMs, as part of VM creation, it tries to install rsync if it's not already installed. Since there is no chance to run any configuration management code yet, it of course tries the default mirrors in the config files in yum.repos.d. This, of course, fails, since 5.11 is long since EOL.

It would be nice if the images were built with modified (or additional) config files in yum.repos.d that point to http://vault.centos.org/ so additional packages can be installed. A `yum update` during build might not be a bad idea either, just to upgrade everything to the latest. (Which is also the reason we probably need an additional file in yum.repos.d so an update doesn't overwrite the file changes).

**Comment by jkugler** [comment]
I realized you'd just need to run `sed` on CentOS-Vault.repo and flip all and `enabled=0` to `enabled=1` as part of your build.

**Comment by grtjn** [comment]
Thanks for reporting this. I blindly copied these packer templates from https://github.com/chef/bento. I never really ran them myself, have just been collecting them for posterity. If you have patches for these packer files, feel free to open a PR against this repo. The old packer templates are long gone in the other repo, they only hold on to the latest versions..

**Comment by jkugler** [comment]
I got this figured out, and they approved adding it back to the active bento builds. Thanks for you help! https://github.com/chef/bento/pull/1100
